apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-ravi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-ravi
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-ravi
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-ravi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-ravi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/ex-registry-zvuu-tenant/appstudio/dc-metro-map-ravi@sha256:f1a56ef1673f55c1c0bbd168a6dc2ac081541854a10349d89172388f677e7c29
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
